In [1]:
import pandas as pd

# Construction Permits Data (not used):

In [2]:
#!/usr/bin/env python

# make sure to install these packages before running:
# pip install pandas
! pip install sodapy

from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.cityofnewyork.us", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(data.cityofnewyork.us,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

# client.timeout = 60

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("ipu4-2q9a", limit=2000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

Collecting sodapy
  Downloading sodapy-2.2.0-py2.py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: requests>=2.28.1 in /usr/local/lib/python3.11/dist-packages (from sodapy) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.28.1->sodapy) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.28.1->sodapy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.28.1->sodapy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.28.1->sodapy) (2024.12.14)
Downloading sodapy-2.2.0-py2.py3-none-any.whl (15 kB)
Installing collected packages: sodapy
Successfully installed sodapy-2.2.0

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [3]:
results_df

,borough,bin__,house__,street_name,job__,job_doc___,job_type,self_cert,block,lot,...,city,state,owner_s_zip_code,site_safety_mgr_s_first_name,site_safety_mgr_s_last_name,site_safety_mgr_business_name,hic_license,act_as_superintendent,permittee_s_other_title,oil_gas
0,MANHATTAN,1088749,1,MADISON AVE,141008987,01,A3,Y,00853,00002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,STATEN ISLAND,5076937,87,BOYLAN STREET,540218539,01,A2,Y,05687,00066,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,STATEN ISLAND,5001506,217,LAFAYETTE AVENUE,540218575,01,A2,Y,00064,00022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,STATEN ISLAND,5067021,170,OAKDALE STREET,540218600,01,A2,Y,05260,00001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,STATEN ISLAND,5058036,273,10 STREET,540218628,01,A2,Y,04242,00045,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,QUEENS,4034646,32-23,84 STREET,440636901,01,A1,N,01414,00064,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,QUEENS,4618903,42-21,165TH STREET,440523970,01,A2,N,05396,00011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,STATEN ISLAND,5170842,456,VILLA AVE,540229377,01,A2,Y,01133,00116,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,QUEENS,4237570,115-60,198TH STREET,440716263,01,A2,Y,11038,00075,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,QUEENS,4271695,118-29,194TH STREET,440715807,01,A2,Y,12615,00047,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
trimmed_df = results_df[['issuance_date','community_board','job_type','bldg_type','residential',]]

In [5]:
trimmed_df

     issuance_date community_board job_type bldg_type residential
0       05/10/2022             105       A3         2         NaN
1       05/10/2022             503       A2         1         YES
2       05/10/2022             501       A2         1         YES
3       05/10/2022             503       A2         1         YES
4       05/10/2022             502       A2         1         YES
...            ...             ...      ...       ...         ...
1995    05/19/2022             403       A1         1         YES
1996    05/19/2022             407       A2         1         YES
1997    05/19/2022             501       A2         1         YES
1998    05/19/2022             412       A2         1         YES
1999    05/19/2022             412       A2         1         YES

[2000 rows x 5 columns]

# Construction Job Applications Data:

In [6]:
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.cityofnewyork.us", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(data.cityofnewyork.us,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

# client.timeout = 60

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("ic3t-wcy2", limit=2000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [7]:
results_df

,job__,doc__,borough,house__,street_name,block,lot,bin__,job_type,job_status,...,sprinkler,zoning_dist3,city_owned,horizontal_enlrgmt,fire_alarm,boiler,fuel_burning,curb_cut,standpipe,fuel_storage
0,321386512,01,BROOKLYN,666,UNION ST,00955,00031,3020058,A1,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,301773613,01,BROOKLYN,412,7 STREET,01000,00017,3021944,A2,P,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,301776077,01,BROOKLYN,208,NORTH 8 STREET,02321,00008,3061967,A2,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,301776291,01,BROOKLYN,933,51 STREET,05645,00066,3137917,A1,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,302163557,01,BROOKLYN,96,ROCKWELL PLACE,02106,07501,3059160,A1,R,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,322085845,01,BROOKLYN,515,BLAKE AVENUE,03766,00001,3327018,DM,X,...,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,301775201,01,BROOKLYN,1629,46 STREET,05434,00074,3128509,DM,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,540239632,01,STATEN ISLAND,122,TAYLOR STREET,00199,00071,5175946,A3,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,500876867,02,STATEN ISLAND,130,LINDENWOOD ROAD,05245,00001,5175089,A2,P,...,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,302073645,01,BROOKLYN,4205,QUENTIN ROAD,07866,00008,3219540,A2,X,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN