In [2]:
from construction_functions import filter_to_new_buildings, connect_to_nyc_data
all_results_df = connect_to_nyc_data("w9ak-ipjd", "filing_date>'2023-12-31T00:00:00.000'")
new_buildings = filter_to_new_buildings(all_results_df)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.
WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

50000 50000

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

50000 100000

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

50000 150000
34300 200000

In [14]:
sum_of_new_builds = len(all_results_df[(all_results_df['filing_date']< '2025-01-01') & (all_results_df['job_type'] == 'New Building')])

In [17]:
sum_of_new_builds

10311

In [19]:
sum_of_new_units_2024 = new_buildings[new_buildings['filing_date']<'2025-01-01']['proposed_dwelling_units'].sum()

In [20]:
sum_of_new_units_2024

np.int64(11626)

In [3]:
new_buildings.sample(25)

,job_filing_number,filing_status,borough,house_no,street_name,initial_cost,building_type,existing_stories,existing_height,existing_dwelling_units,proposed_no_of_stories,proposed_height,proposed_dwelling_units,filing_date,current_status_date,first_permit_date,latitude,longitude,job_type
2417,Q00663885-S6,Permit Entire,QUEENS,45-02,NORTHERN BOULEVARD,7200,Other,NaN,NaN,NaN,2,37,0,2024-01-08,2024-12-23T19:51:26.000,2024-12-23T00:00:00.000,40.753855,-73.917447,New Building
144437,X00592786-S5,Permit Entire,BRONX,3220,TIEMANN AVENUE,0,Other,NaN,NaN,NaN,4,38,38,2024-11-27,2024-12-09T21:46:07.000,2024-12-09T00:00:00.000,40.874275,-73.841844,New Building
131540,B00738222-S1,LOC Issued,BROOKLYN,345,BERGEN STREET,0,Other,NaN,NaN,NaN,6,60,6,2024-10-29,2025-01-02T16:27:28.000,2024-12-23T00:00:00.000,40.682711,-73.980152,New Building
164581,B01108767-S6,Permit Entire,BROOKLYN,455,KEAP STREET,0,Other,NaN,NaN,NaN,4,60,2,2025-01-23,2025-02-12T18:58:04.000,2025-02-12T00:00:00.000,40.712508,-73.952454,New Building
71166,Q01064523-I1,Permit Entire,QUEENS,134-26,57 AVENUE,0,2 Family,NaN,NaN,NaN,3,35,2,2024-06-12,2024-11-12T22:17:07.000,2024-11-12T00:00:00.000,40.747206,-73.830730,New Building
110646,B01088570-S1,Permit Entire,BROOKLYN,3700,ATLANTIC AVENUE,0,Other,NaN,NaN,NaN,1,15,0,2024-09-12,2024-10-03T16:06:34.000,2024-10-03T00:00:00.000,40.573679,-74.002973,New Building
7508,X00960081-S7,Permit Entire,BRONX,2267,ANDREWS AVENUE NORTH,0,Other,NaN,NaN,NaN,6,70,25,2024-01-19,2025-01-27T21:24:52.000,2025-01-27T00:00:00.000,40.860763,-73.907976,New Building
56286,Q00552707-S6,Permit Entire,QUEENS,678,VIRGINIA STREET,0,Other,NaN,NaN,NaN,1,14,1,2024-05-09,2025-02-13T15:17:02.000,2025-02-13T00:00:00.000,40.604207,-73.740459,New Building
31141,Q00705327-S6,Permit Entire,QUEENS,122-05,MERRICK BOULEVARD,0,Other,NaN,NaN,NaN,1,18,0,2024-03-14,2025-01-28T19:46:29.000,2025-01-28T00:00:00.000,40.683695,-73.769561,New Building
115609,Q00811433-S9,LOC Issued,QUEENS,42-09,HAMPTON STREET,0,Other,NaN,NaN,NaN,6,72,10,2024-09-24,2024-11-26T18:36:57.000,2024-10-16T00:00:00.000,40.744779,-73.877879,New Building
162196,X01103533-S2,Permit Entire,BRONX,869,EAST 175 STREET,0,Other,NaN,NaN,NaN,4,50,13,2025-01-16,2025-02-04T20:14:54.000,2025-02-04T00:00:00.000,40.839999,-73.888481,New Building
3069,S00807316-S4,LOC Issued,STATEN ISLAND,780,IONIA AVENUE,0,1 Family,NaN,NaN,NaN,2,25,1,2024-01-09,2024-07-30T14:04:07.000,2024-05-28T00:00:00.000,40.536694,-74.198683,New Building
116412,X01072612-S6,Permit Entire,BRONX,585,JACKSON AVENUE,0,Other,NaN,NaN,NaN,9,75,80,2024-09-25,2025-02-28T16:35:27.000,2025-02-04T00:00:00.000,40.814117,-73.908770,New Building
74439,B00561243-S3,Permit Entire,BROOKLYN,215,CALYER STREET,0,Other,NaN,NaN,NaN,5,50,5,2024-06-20,2024-10-04T20:29:29.000,2024-10-04T00:00:00.000,40.728636,-73.951772,New Building
98404,Q01096535-I1,Permit Entire,QUEENS,147-43,DELAWARE AVENUE,0,2 Family,NaN,NaN,NaN,2,35,2,2024-08-14,2025-02-24T13:19:45.000,2025-01-06T00:00:00.000,40.756912,-73.815513,New Building
132566,S00739621-S5,Permit Entire,STATEN ISLAND,3002,RICHMOND TERRACE,0,Other,NaN,NaN,NaN,2,35,2,2024-10-31,2025-01-28T21:33:08.000,2025-01-28T00:00:00.000,40.637074,-74.159940,New Building
6390,S00766081-S2,LOC Issued,STATEN ISLAND,41,HIGHLAND ROAD,0,2 Family,NaN,NaN,NaN,3,30,2,2024-01-17,2024-03-14T20:12:26.000,2024-02-16T00:00:00.000,40.550746,-74.143918,New Building
143617,Q00713167-S9,Permit Entire,QUEENS,38-26,28 STREET,0,Other,NaN,NaN,NaN,6,60,13,2024-11-26,2025-01-30T14:25:37.000,2025-01-09T00:00:00.000,40.754656,-73.934648,New Building
104418,X01086590-S1,Permit Entire,BRONX,727,EAST 215 STREET,0,Other,NaN,NaN,NaN,4,50,15,2024-08-28,2025-01-03T16:40:15.000,2025-01-03T00:00:00.000,40.880302,-73.863462,New Building
115683,X01072612-S5,Permit Entire,BRONX,585,JACKSON AVENUE,0,Other,NaN,NaN,NaN,9,75,80,2024-09-24,2025-02-26T01:56:52.000,2025-02-07T00:00:00.000,40.814117,-73.908770,New Building
15110,Q00766750-S5,Permit Entire,QUEENS,315,BEACH 15 STREET,0,2 Family,NaN,NaN,NaN,4,40,2,2024-02-06,2025-01-15T20:04:16.000,2025-01-15T00:00:00.000,40.598215,-73.749042,New Building
65442,B01030647-S2,Permit Issued,BROOKLYN,133,CARLTON AVENUE,0,Other,NaN,NaN,NaN,4,50,6,2024-05-30,2025-02-04T18:50:06.000,2025-02-04T00:00:00.000,40.693735,-73.973019,New Building
120550,B00930555-S8,Permit Entire,BROOKLYN,1728,EAST 2 STREET,0,1 Family,NaN,NaN,NaN,3,35,1,2024-10-03,2024-11-07T19:44:38.000,2024-11-07T00:00:00.000,40.607549,-73.971660,New Building
114008,B01020143-S2,Permit Entire,BROOKLYN,217,19 STREET,0,2 Family,NaN,NaN,NaN,4,50,2,2024-09-19,2025-02-07T21:50:00.000,2025-02-07T00:00:00.000,40.662983,-73.993079,New Building
142000,X00751697-Z4,LOC Issued,BRONX,2,ORCHARD BEACH,0,Other,NaN,NaN,NaN,2,26,0,2024-11-21,2025-02-27T22:15:26.000,2024-12-13T00:00:00.000,40.866373,-73.793111,New Building

In [4]:
new_buildings['building_type'].unique()

array(['Other', '2 Family', '1 Family', '3 Family'], dtype=object)

In [11]:
df2024 = new_buildings[new_buildings['filing_date'] < '2025-01-01']

In [12]:
df2024

,job_filing_number,filing_status,borough,house_no,street_name,initial_cost,building_type,existing_stories,existing_height,existing_dwelling_units,proposed_no_of_stories,proposed_height,proposed_dwelling_units,filing_date,current_status_date,first_permit_date,latitude,longitude,job_type
15,Q00976583-S1,LOC Issued,QUEENS,149-18 GAR,BEECH AVENUE,0,Other,NaN,NaN,NaN,1,12,0,2024-01-01,2024-11-21T23:02:06.000,2024-10-17T00:00:00.000,40.758899,-73.813703,New Building
26,Q00976583-I1,Permit Entire,QUEENS,149-18 GAR,BEECH AVENUE,0,Other,NaN,NaN,NaN,1,12,0,2024-01-01,2024-03-14T17:36:02.000,2024-03-14T00:00:00.000,40.758899,-73.813703,New Building
29,Q00928782-I1,Permit Entire,QUEENS,167-03 GAR,65 AVENUE,0,Other,NaN,NaN,NaN,1,12,0,2024-01-01,2024-05-31T19:36:20.000,2024-05-31T00:00:00.000,40.736669,-73.801774,New Building
41,Q00928782-S1,Permit Entire,QUEENS,167-03 GAR,65 AVENUE,0,Other,NaN,NaN,NaN,1,12,0,2024-01-01,2024-10-31T12:54:28.000,2024-10-31T00:00:00.000,40.736669,-73.801774,New Building
49,Q00609018-S1,LOC Issued,QUEENS,132-28 GAR,57 ROAD,0,2 Family,NaN,NaN,NaN,1,12,0,2024-01-01,2024-06-17T14:42:04.000,2024-05-10T00:00:00.000,40.746693,-73.832854,New Building
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154903,Q01064523-S6,Permit Entire,QUEENS,134-26,57 AVENUE,0,2 Family,NaN,NaN,NaN,3,35,2,2024-12-25,2025-02-05T16:59:47.000,2025-02-05T00:00:00.000,40.747206,-73.830730,New Building
154909,Q01064523-S7,Permit Entire,QUEENS,134-26,57 AVENUE,0,2 Family,NaN,NaN,NaN,3,35,2,2024-12-25,2025-02-05T16:54:15.000,2025-02-05T00:00:00.000,40.747206,-73.830730,New Building
154924,Q00845458-S1,Permit Entire,QUEENS,215-19 GAR,36 AVENUE,0,Other,NaN,NaN,NaN,1,12,0,2024-12-25,2025-01-02T16:02:33.000,2025-01-02T00:00:00.000,40.768714,-73.769230,New Building
155074,Q00881657-S1,Permit Entire,QUEENS,38-02 GAR,CLEARVIEW EXPRESSWAY,0,Other,NaN,NaN,NaN,1,11,0,2024-12-26,2025-01-28T16:07:50.000,2025-01-28T00:00:00.000,40.763962,-73.780250,New Building
155670,X01143746-S8,Permit Entire,BRONX,1801,WEEKS AVENUE,0,Other,NaN,NaN,NaN,12,129,99,2024-12-30,2025-01-06T19:16:27.000,2025-01-06T00:00:00.000,40.846910,-73.907388,New Building